# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker_Hub'
        repository: 't3winc/blog'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'npm install typed-rest-client --save'
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'curl -LO https://storage.googleapis.com/container-structure-test/v1.10.0/container-structure-test-linux-amd64 && mv container-structure-test-linux-amd64 container-structure-test && chmod +x container-structure-test && sudo mv container-structure-test /usr/local/bin/'
    - task: ContainerStructureTest@0
      displayName: Test the Image
      inputs:
        dockerRegistryServiceConnection: 'Docker_Hub'
        repository: '''t3winc/blog'''
        configFile: '''**/test/DockerTest/unit-test.yaml'''
        testRunTitle: '''Container Structure Test'''
        failTaskOnFailedTests: true

      
