# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker_Hub'
        repository: 'schulzdl/blog'
        command: 'build'
        Dockerfile: 'Dockerfile'
        tags: '$(tag)'
        
- task: CmdLine@2
  inputs:
    script: 'npm install typed-rest-client --save'
    
- task: ContainerStructureTest@0
  inputs:
    dockerRegistryServiceConnection: 'Docker_Hub'
    repository: 'schulzdl/blog'
    configFile: '**/test/DockerTest/unit-test.yaml'
    testRunTitle: 'Container Structure Test'
    failTaskOnFailedTests: true