// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace DeployViaFTP.PageObects.ToolbarClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class Toolbar
    {
        
        /// <summary>
        /// StartPowerShellISE_as_Admin - Use 'StartPowerShellISE_as_AdminParams' to pass parameters into this method.
        /// </summary>
        public void StartPowerShellISE_as_Admin()
        {

            // Launch '%windir%\System32\WindowsPowerShell\v1.0\powershell_ise.exe'
            ApplicationUnderTest powershell_iseApplication = ApplicationUnderTest.Launch(this.StartPowerShellISE_as_AdminParams.ExePath, this.StartPowerShellISE_as_AdminParams.AlternateExePath);
        }
        
        #region Properties
        public virtual StartPowerShellISE_as_AdminParams StartPowerShellISE_as_AdminParams
        {
            get
            {
                if ((this.mStartPowerShellISE_as_AdminParams == null))
                {
                    this.mStartPowerShellISE_as_AdminParams = new StartPowerShellISE_as_AdminParams();
                }
                return this.mStartPowerShellISE_as_AdminParams;
            }
        }
        #endregion
        
        #region Fields
        private StartPowerShellISE_as_AdminParams mStartPowerShellISE_as_AdminParams;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'StartPowerShellISE_as_Admin'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class StartPowerShellISE_as_AdminParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%windir%\System32\WindowsPowerShell\v1.0\powershell_ise.exe'
        /// </summary>
        public string ExePath = "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell_ise.exe";
        
        /// <summary>
        /// Launch '%windir%\System32\WindowsPowerShell\v1.0\powershell_ise.exe'
        /// </summary>
        public string AlternateExePath = "%windir%\\System32\\WindowsPowerShell\\v1.0\\powershell_ise.exe";
        #endregion
    }
}
