pipeline {
    agent any
    stages {
        stage("Test"){
            steps {
                sh "dotnet test ./test/Selenium/blog_xunit/blog_xunit.csproj --test-adapter-path:. --logger:xunit"
            }
            post {
                always {
                    xunit (
                        thresholds: [ skipped(failureThreshold: '0'), failed(failureThreshold: '0')],
                        tools: [ xUnitDotNet(pattern: '**/TestResults.xml')]
                    )
                }
            }
        }
    }
}